<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>dc8941e3-0794-4122-a9d7-f3c18746f746</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Medications.Api\Medications.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Scalar.Aspire" />
  </ItemGroup>

</Project>
